version: '3.8'
services:
  dbpostgres:
    image: postgres
    container_name: dbpostgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
  dbpostgrestest:
    image: postgres
    container_name: dbtest
    ports:
      - '5433:5432'
    restart: always
    env_file:
    - ./.env
    volumes:
      - postgres-db-test:/var/lib/postgresql/data
volumes:
  postgres-db:
  postgres-db-test: