services:
  dbpostgrestest:
    image: postgres
    container_name: dbpostgrestest
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: