version: '3.9'
services:
  fastapi:
    build: .
    container_name: gestorlab_api
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/app
    entrypoint:
      [
        "/app/wait-for-it.sh",
        "${DATABASE_HOST}", ## aqui utiliza a variável de ambiente
        "--",
        "sh",
        "-c",
        "alembic revision --autogenerate -m '' && alembic upgrade head && python create_utils.py && uvicorn main:app --host 0.0.0.0 --port 8000"
      ]
