"""Add colunm image in laboratory

Revision ID: 12e2fd687343
Revises: 26ac0767f6b5
Create Date: 2024-07-22 15:39:35.328945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '12e2fd687343'
down_revision: Union[str, None] = '26ac0767f6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laboratorios', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laboratorios', 'image')
    # ### end Alembic commands ###
