"""

Revision ID: 1b6e1c24eae5
Revises: 06f750e723eb
Create Date: 2024-08-09 13:55:08.754567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1b6e1c24eae5'
down_revision: Union[str, None] = '06f750e723eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projetos', 'image')
    # ### end Alembic commands ###
