"""Update new associetion

Revision ID: 7efabcee7eaa
Revises: 12e2fd687343
Create Date: 2024-07-22 17:23:17.149881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '7efabcee7eaa'
down_revision: Union[str, None] = '12e2fd687343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratorio_pending',
    sa.Column('laboratorio_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('pending_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.ForeignKeyConstraint(['pending_id'], ['pendings.id'], )
    )
    op.add_column('pendings', sa.Column('id_lab', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))
    op.add_column('pendings', sa.Column('id_project', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))
    op.alter_column('pendings', 'id_user',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('pendings_id_user_fkey', 'pendings', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('pendings_id_user_fkey', 'pendings', 'usuario', ['id_user'], ['id'])
    op.alter_column('pendings', 'id_user',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('pendings', 'id_project')
    op.drop_column('pendings', 'id_lab')
    op.drop_table('laboratorio_pending')
    # ### end Alembic commands ###
