"""Update

Revision ID: a93a87f9cecd
Revises: 7efabcee7eaa
Create Date: 2024-07-22 17:50:52.831116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'a93a87f9cecd'
down_revision: Union[str, None] = '7efabcee7eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pendings', 'matricula_user',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pendings', 'matricula_user',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
