"""Migração inicial!

Revision ID: fb27719ece13
Revises: 
Create Date: 2024-04-15 19:23:39.682580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb27719ece13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('primeiro_nome', sa.String(length=256), nullable=False),
    sa.Column('segundo_nome', sa.String(length=256), nullable=False),
    sa.Column('primeiro_acesso', sa.Boolean(create_constraint=True), nullable=False),
    sa.Column('matricula', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('tel', sa.BigInteger(), nullable=True),
    sa.Column('senha', sa.String(length=256), nullable=False),
    sa.Column('data_inicial', sa.String(length=256), nullable=False),
    sa.Column('data_atualizacao', sa.String(length=256), nullable=False),
    sa.Column('tag', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('laboratorios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coordenador_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('sobre', sa.String(length=5000), nullable=False),
    sa.Column('descricao', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('data_inicial', sa.String(length=256), nullable=False),
    sa.Column('data_up', sa.String(length=256), nullable=False),
    sa.Column('template', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coordenador_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projetos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=256), nullable=False),
    sa.Column('descricao', sa.String(length=5000), nullable=True),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('data_inicial', sa.String(length=256), nullable=False),
    sa.Column('data_up', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('usuario_laboratorio',
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('laboratorio_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], )
    )
    op.create_table('usuario_projeto',
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('projeto_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_projeto')
    op.drop_table('usuario_laboratorio')
    op.drop_table('projetos')
    op.drop_table('laboratorios')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
