from models.laboratorio import Laboratorio
from models.projeto import Projeto
from models.permissao import Permissao
from models.permissaoOfLab import PermissaoOfLab
from models.genero import Genero
from models.pending import Pending
from models.usuario import Usuario
from models.permissaoLab import PermissaoLab
from models.endereco import Endereco